# Exported from Render on 2026-10-04T07:17:12Z
version: "1"
services:
- type: web
  name: philthysports-api-v9
  runtime: python
  repo: https://github.com/filthycashout/betp-app-
  plan: free
  envVars:
  - key: PHILTHY_CORS_ORIGINS
    sync: false
  - key: CREDENTIAL_ROTATION_CONFIRMED
    sync: false
  - key: PHILTHY_SIGNAL_LOG_DIR
    sync: false
  region: oregon
  buildCommand: pip install -r backend/requirements.txt
  startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
  autoDeployTrigger: commit
